<?php

namespace Tests\Unit\Domain;

use Tests\TestCase;
use LaravelItalia\Domain\Article;

class ArticleTest extends TestCase
{
    /**
     * @var Article
     */
    private $article;

    public function setUp()
    {
        $this->article = new Article();
        $this->article->title = 'test title';
        $this->article->published_at = null;

        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testIsPublished()
    {
        $this->assertFalse($this->article->isPublished());

        $this->article->published_at = \Carbon\Carbon::now();

        $this->assertTrue($this->article->isPublished());
    }

    public function testPublish()
    {
        $expectedPublicationDate = \Carbon\Carbon::now();

        $this->article->publish($expectedPublicationDate);

        $this->assertEquals($expectedPublicationDate, $this->article->published_at);
    }

    public function testUnpublish()
    {
        $this->article->published_at = \Carbon\Carbon::now();

        $this->article->unpublish();

        $this->assertNull($this->article->published_at);
    }
}
